include: package:lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_enum_constant_in_switch: error

linter:
  rules:
    - always_declare_return_types
    - camel_case_types
    - camel_case_extensions
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - file_names
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures
    - unsafe_html
    - void_checks
