targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: true
          explicit_to_json: true

      xayn_discovery_engine|property_mapEvent:
        enabled: true

builders:
  xayn_discovery_engine|property_mapEvent:
    import: "lib/src/generators/builder.dart"
    builder_factories: [ "mapEventBuilder" ]
    build_extensions: { ".dart": [ ".mapEvent.g.part" ] }
    auto_apply: dependents
    build_to: cache
    applies_builders: [ "source_gen|combining_builder" ]
