name: xayn_discovery_engine
description: Xayn Discovery Engine package for Dart VM and web.
version: 0.1.0
homepage: https://github.com/xaynetwork/xayn_discovery_engine/
publish_to: none

environment:
  sdk: '>=2.14.2 <3.0.0'

dependencies:
  async: ^2.8.2
  crypto: ^3.0.1
  equatable: ^2.0.3
  freezed_annotation: ^1.1.0
  hive: ^2.0.5
  http: ^0.13.4
  http_retry: ^0.2.0
  json_annotation: ^4.4.0
  logger: ^1.1.0
  meta: ^1.7.0
  universal_platform: ^1.0.0+1
  uuid: ^3.0.5
  async_bindgen_dart_utils:
    git:
      url: https://github.com/xaynetwork/xayn_async_bindgen.git
      path: async_bindgen_dart_utils
      ref: fe195d99954c691c5e606ebbb3c77d371ba0e65b

dev_dependencies:
  build_runner: ^2.1.7
  freezed: ^1.1.1
  hive_generator: ^1.1.2
  json_serializable: ^6.1.4
  lints: ^1.0.1
  test: ^1.20.1
  ffigen: ^4.0.0
