name: xayn_discovery_engine
description: Xayn Discovery Engine package for Dart VM and web.
version: 0.1.0
homepage: https://github.com/xaynetwork/xayn_discovery_engine/

environment:
  sdk: '>=2.14.2 <3.0.0'


dependencies:
  equatable: 2.0.3
  uuid: 3.0.5

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
