name: xayn_discovery_engine
description: Xayn Discovery Engine package for Dart VM and web.
version: 0.1.0+change.me.to.commit.ref
homepage: https://github.com/xaynetwork/xayn_discovery_engine/
publish_to: https://xayn.jfrog.io/artifactory/api/pub/dart.yellow.private

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  async: ^2.8.2
  csv: ^5.0.1
  crypto: ^3.0.2
  equatable: ^2.0.3
  freezed_annotation: ^1.1.0
  fuzzy: ^0.4.0-nullsafety.0
  hive: ^2.2.2
  http: ^0.13.4
  http_retry: ^0.2.0
  json_annotation: ^4.5.0
  logger: ^1.1.0
  meta: ^1.7.0
  universal_platform: ^1.0.0+1
  uuid: ^3.0.6
  async_bindgen_dart_utils:
    hosted: https://xayn.jfrog.io/artifactory/api/pub/dart.yellow.private
    version: 0.1.0+change.me.to.commit.ref
  source_gen: ^1.2.2
  build: ^2.3.0
  analyzer: ^3.4.1

dependency_overrides:
  async_bindgen_dart_utils:
    path: ../async_bindgen_dart_utils/

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^1.1.1
  hive_generator: ^1.1.3
  json_serializable: ^6.2.0
  lints: ^2.0.0
  test: ^1.21.1
  ffigen: ^6.0.1
  mockito: ^5.2.0
