name: xayn_discovery_engine
description: Xayn Discovery Engine package for Dart VM and web.
version: 0.1.0
homepage: https://github.com/xaynetwork/xayn_discovery_engine/

environment:
  sdk: '>=2.14.2 <3.0.0'


dependencies:
  equatable: 2.0.3
  freezed_annotation: 0.15.0
  hive: 2.0.4
  json_annotation: 4.3.0
  uuid: 3.0.5

dev_dependencies:
  build_runner: 2.1.5
  freezed: 0.15.1+1
  hive_generator: 1.1.1
  json_serializable: 6.0.1
  lints: 1.0.1
  test: 1.19.3
