[package]
name = "xayn-discovery-engine-bindings"
version = "0.1.0"
edition = "2018"
license = "AGPL-3.0-only"

[dependencies]
async-bindgen = "0.1.0"

[dev-dependencies]
async-bindgen-gen-dart = "0.1.0"

[build-dependencies]
cbindgen = "=0.20.0"
heck = "0.4.0"

[lib]
crate-type = ["cdylib", "staticlib"]
