[package]
name = "xayn-discovery-engine-providers"
version = "0.1.0"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
chrono = { version = "0.4.19", default_features = false, features = ["clock", "serde"] }
derive_more = { version = "0.99.17", default-features = false, features = ["display"] }
displaydoc = "0.2.3"
itertools = "0.10.3"
lazy_static = "1.4.0"
maplit = "1.0.2"
reqwest = { version = "0.11.9", features = ["json", "rustls-tls"], default-features = false }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
serde_path_to_error = "0.1.7"
thiserror = "1.0.30"
url = "2.2.2"

[dev-dependencies]
claim = "0.5.0"
tokio = { version = "1.17.0", features = ["rt", "macros"] }
wiremock = "0.5.10"
