[package]
name = "xayn-discovery-engine-providers"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = "AGPL-3.0-only"

[dependencies]
<<<<<<< HEAD
async-trait = "0.1.57"
chrono = { version = "0.4.21", default-features = false, features = ["clock", "serde"] }
derive_more = { version = "0.99.17", default-features = false, features = ["display", "deref"] }
displaydoc = "0.2.3"
itertools = "0.10.3"
maplit = "1.0.2"
once_cell = "1.13.1"
regex = { version = "1.6.0", features = ["unicode-gencat"] }
reqwest = { version = "0.11.11", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
=======
async-trait = { workspace = true }
chrono = { workspace = true, features = ["clock", "serde"] }
derive_more = { workspace = true }
displaydoc = { workspace = true }
itertools = { workspace = true }
maplit = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
>>>>>>> main
serde_path_to_error = "0.1.8"
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
wiremock = { workspace = true }
