[package]
name = "xayn-discovery-engine-providers"
version = "0.1.0"
license = "AGPL-3.0-only"
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["wasmbind", "serde"] }
displaydoc = "0.2.3"
itertools = "0.10.3"
lazy_static = "1.4.0"
maplit = "1.0.2"
reqwest = { version = "0.11.9", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.30"
xayn-discovery-engine-core = { path = "../core" }

[dev-dependencies]
claim = "0.5.0"
tokio = { version = "1.15.0", features = ["rt", "macros"] }
wiremock = "0.5"
