name: Build service docker image

inputs:
  archive_name:
    description: Name of the archive to upload
    type: string
    required: true
  image_name:
    description: Name of docker image
    type: string
    required: true
  platform:
    description: Platform for which we build the image (arm64 or amd64)
    type: choice
    options:
      - arm64
      - amd64
    required: true

runs:
  using: "composite"
  steps:
    - name: Download artifacts
      id: artifacts
      uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
      with:
        name: ${{ inputs.archive_name }}

    - name: Create docker image
      shell: bash
      run: |
        tar -xvf "${{ inputs.archive_name }}.tar"
        cd "./${{ inputs.archive_name }}"
        docker build --platform linux/${{ inputs.platform }} -t "${{ inputs.image_name }}" .

