#!/bin/sh

set -eux
cd "$(dirname $0)"

function build_rust() {
    cd discovery_engine_core
    cargo check --quiet 2>/dev/null
    cargo build
    cd ..
}

function test_rust() {
    cd discovery_engine_core

    cargo +nightly fmt --all -- --check
    cargo sort --grouped --workspace --check

    # Workaround for code-gen bug
    cargo check --quiet 2>/dev/null || :

    cargo clippy --all-targets

    cargo test

    cd ..
}

function build_bindgen() {
    build_rust

    cd discovery_engine
    dart pub get
    dart run ffigen --config ffigen.yaml
    cd ..

    cd discovery_engine_core
    #TODO rename to cargo-async-bindgen and use cargo async-bindgen
    ~/.cargo/bin/async-bindgen-gen-dart \
        --ffi-class XaynDiscoveryEngineBindingsFfi \
        --genesis ../discovery_engine/lib/src/ffi/genesis.ffigen.dart
    cd ..

    # ios needs the original headers, as wee need to statically link in the
    # binary code generated by rust (instead of loading it as a shared library)
    cp ./discovery_engine_core/bindings/include/*.h ./discovery_engine_flutter/ios/Classes/
}

function install_async_bindgen_cli() {
    cargo install \
        --git https://github.com/xaynetwork/xayn_async_bindgen.git \
        async-bindgen-gen-dart \
        "$@"
}

CMD="$1"
shift
"$CMD" "$@"

