#!/bin/sh

# Rung by passing in the function name to call as first parameter to the script.
# E.g.  ./tmp_script.sh build_rust
#
# Be aware that this script will in a follow up PR be replaced with an ob runner.

set -eux
cd "$(dirname $0)"

function build_rust() {
    cd discovery_engine_core
    cargo check --quiet 2>/dev/null
    cargo build
    cd ..
}

function test_rust() {
    cd discovery_engine_core

    cargo +nightly fmt --all -- --check
    cargo sort --grouped --workspace --check

    # Workaround for code-gen bug
    cargo check --quiet 2>/dev/null || :

    cargo clippy --all-targets

    cargo test

    cd ..
}

function find_cargo_bin_dir() {
    # Doesn't respect cargo config option, but good enough for us for now
    echo "${CARGO_INSTALL_ROOT:-${CARGO_HOME:-$HOME/.cargo}}/bin"
}

function build_bindgen() {
    build_rust

    cd discovery_engine
    dart pub get
    dart run ffigen --config ffigen.yaml
    cd ..

    cd discovery_engine_core
    "$(find_cargo_bin_dir)/async-bindgen-gen-dart" \
        --ffi-class XaynDiscoveryEngineBindingsFfi \
        --genesis ../discovery_engine/lib/src/ffi/genesis.ffigen.dart
    cd ..

    # ios needs the original headers, as wee need to statically link in the
    # binary code generated by rust (instead of loading it as a shared library)
    cp ./discovery_engine_core/bindings/include/*.h ./discovery_engine_flutter/ios/Classes/
}

function test_dart_with_bindgen() {
    build_bindgen
    cd discovery_engine
    dart test
    cd ..
}

function install_async_bindgen_cli() {
    cargo install \
        --git https://github.com/xaynetwork/xayn_async_bindgen.git \
        async-bindgen-gen-dart \
        "$@"
}

CMD="$1"
shift
"$CMD" "$@"

