[package]
name = "web-api"
version = "0.1.0"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
chrono = { version = "0.4.19", default-features = false, features = ["serde"] }
derive_more = { version = "0.99.17", default-features = false, features = ["display", "from"] }
dotenvy = "0.15.1"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.1.2", features = ["serde", "v4"] }
warp = "0.3.2"
xayn-discovery-engine-ai = { path = "../ai/ai" }
xayn-discovery-engine-bert = { path = "../ai/bert" }
xayn-discovery-engine-core = { path = "../core" }
xayn-discovery-engine-providers = { path = "../providers" }
xayn-discovery-engine-tokenizer = { path = "../ai/tokenizer" }
