name: xayn_discovery_engine_flutter
description: Xayn Discovery Engine package for Flutter bundled with binaries.
version: 0.1.0
homepage: https://github.com/xaynetwork/xayn_discovery_engine/
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  xayn_discovery_engine:
    git:
      url: git@github.com:xaynetwork/xayn_discovery_engine_release.git
      ref: main
      path: discovery_engine

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

dependency_overrides:
  xayn_discovery_engine:
    path: "../discovery_engine"

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.xayn.xayn_discovery_engine_flutter
        pluginClass: XaynDiscoveryEngineFlutterPlugin
      ios:
        pluginClass: XaynDiscoveryEngineFlutterPlugin
