name: xayn_discovery_engine_flutter
description: Xayn Discovery Engine package for Flutter bundled with binaries.
version: 0.1.0
homepage: https://github.com/xaynetwork/xayn_discovery_engine/
publish_to: none

environment:
  sdk: '>=2.17.3 <3.0.0'
  flutter: '>=3.0.2'

dependencies:
  flutter:
    sdk: flutter
  xayn_discovery_engine:
    git:
      url: https://gitlab.com/xayn/xayn_discovery_engine_release
      ref: change_me_to_commit_ref
      path: discovery_engine

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

dependency_overrides:
  xayn_discovery_engine:
    path: "../discovery_engine"

flutter:
  assets:
    # We need to include the manifest file from Discovery Engine to bundle it with the app
    - packages/xayn_discovery_engine/assets/asset_manifest.json

  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.xayn.xayn_discovery_engine_flutter
        pluginClass: XaynDiscoveryEngineFlutterPlugin
      ios:
        pluginClass: XaynDiscoveryEngineFlutterPlugin
