name: example
description: A simple example of using Discovery Engine
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  xayn_discovery_engine:
    path: ../

dev_dependencies:
  lints: ^1.0.0
