[package]
name = "xayn-discovery-engine-bert"
version = "0.1.0"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
derive_more = { version = "0.99.17", default-features = false, features = ["deref", "from"] }
displaydoc = "0.2.3"
float-cmp = "0.9.0"
# to be kept in sync with tract-core
ndarray = { version = "=0.15.3", features = ["serde"] }
rayon = "1.5.1"
serde = { version = "1.0.136", features = ["derive"] }
thiserror = "1.0.30"
tract-onnx = "0.16.1"
xayn-discovery-engine-tokenizer = { path = "../tokenizer" }

[dev-dependencies]
criterion = { version = "0.3.5", features = ["html_reports"] }
csv = { version = "1.1.6" }
indicatif = { version = "0.16.2" }
onnxruntime = { version = "0.0.13" }
xayn-discovery-engine-test-utils = { path = "../test-utils" }

[[example]]
name = "mbert"
test = false

[[example]]
name = "validate"
test = false

[[bench]]
name = "mbert"
harness = false
test = false
