[package]
name = "xayn-ai-test-utils"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = "AGPL-3.0-only"
publish = false

[features]
integration = ["sqlx", "anyhow", "scopeguard", "chrono", "rand", "once_cell", "reqwest", "mime", "serde_json", "tokio"]

[dependencies]
float-cmp = { workspace = true }
ndarray = { workspace = true }
uuid = { workspace = true }
sqlx = { workspace = true, optional = true }
anyhow = { workspace = true, optional = true }
scopeguard = { version = "1.1.0", optional = true }
chrono = { workspace=true, optional= true }
rand = { workspace=true, optional= true }
once_cell = { workspace=    true, optional=true }
reqwest = { workspace= true, optional=true }
mime = { workspace = true, optional= true }
serde_json = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }

[dev-dependencies]
#todo opt dep
regex = { workspace= true}
