name: Setup ci job

inputs:
  rust:
    description: Setup rust
    default: "false"
    required: false
  cache-key:
    description: An optional key that is added to the automatic cache key
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Load .env
      uses: xom9ikk/dotenv@v2

    - uses: Swatinem/rust-cache@v2.2.0
      if: inputs.rust != 'false'
      with:
        key: ${{ inputs.cache-key }}
        workspaces: ${{ env.RUST_WORKSPACE }} -> target

    - name: Configure cargo
      shell: bash
      run: |
        # We do this since multiple jobs are run on the same CI build server,
        # and if multiple cargo build jobs run at max parallelism it ends up
        # slowing all builds down.
        echo "CARGO_BUILD_JOBS=6" >> $GITHUB_ENV
