name: Setup ci job

inputs:
  rust:
    description: Setup rust
    default: "false"
    required: false
  cache-key:
    description: An optional key that is added to the automatic cache key
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Load .env
      uses: xom9ikk/dotenv@eff1dce037c4c0143cc4180a810511024c2560c0 # v2

    - uses: Swatinem/rust-cache@359a70e43a0bb8a13953b04a90f76428b4959bb6 # v2.2.0
      if: inputs.rust != 'false'
      with:
        key: ${{ inputs.cache-key }}
        workspaces: ${{ env.RUST_WORKSPACE }} -> target

    - name: Configure cargo
      shell: bash
      run: |
        # We do this since multiple jobs are run on the same CI build server,
        # and if multiple cargo build jobs run at max parallelism it ends up
        # slowing all builds down.
        echo "CARGO_BUILD_JOBS=6" >> $GITHUB_ENV

    - name: Jfrog authentication
      shell: bash
      if: ${{ inputs.jfrog_token != 'false' }}
      env:
          JFROG_TOKEN: ${{ inputs.jfrog_token }}
      run: |
        if [ -z "${JFROG_TOKEN}" ]; then
          echo "JFROG access token missing"
          exit 1
        fi
        echo "${JFROG_TOKEN}" | dart pub token add "https://xayn.jfrog.io/artifactory/api/pub/dart.xayn.private"

    - name: dart deps
      shell: bash
      if: ${{ inputs.dart != 'false' }}
      run: just dart-deps
