name: Setup ci job

inputs:
  cache-key:
    description: An optional key that is added to the automatic cache key
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Load .env
      uses: xom9ikk/dotenv@de1ff27d319507880e6621e4d47424c677d95f68 # v2.2.0

    - name: Setup missing libs
      shell: bash
      run: |
        apt-get update
        apt-get install pkg-config libxml2

    - name: Configure cargo
      shell: bash
      run: |
        # We do this since multiple jobs are run on the same CI build server,
        # and if multiple cargo build jobs run at max parallelism it ends up
        # slowing all builds down.
        echo "CARGO_BUILD_JOBS=6" >> $GITHUB_ENV
        echo "CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse" >> $GITHUB_ENV

    # This action uses env vars for hash used in the key, therefore we keep it as last.
    - uses: Swatinem/rust-cache@2656b87321093db1cb55fbd73183d195214fdfd1 # v2.5.0
      with:
        key: ${{ inputs.cache-key }}

