name: Setup ci job

inputs:
  cache-key:
    description: An optional key that is added to the automatic cache key
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Load .env
      uses: xom9ikk/dotenv@0aa0b3b90e18d0e4d4b4ba4d8f9e0ae6e6a7049a # v2.1.1

    - name: Configure cargo
      shell: bash
      run: |
        # We do this since multiple jobs are run on the same CI build server,
        # and if multiple cargo build jobs run at max parallelism it ends up
        # slowing all builds down.
        echo "CARGO_BUILD_JOBS=6" >> $GITHUB_ENV

    # This action uses env vars for hash used in the key, therefore we keep it as last. 
    - uses: Swatinem/rust-cache@359a70e43a0bb8a13953b04a90f76428b4959bb6 # v2.2.0
      with:
        key: ${{ inputs.cache-key }}

