name: Setup ci job

inputs:
  cache-key:
    description: An optional key that is added to the automatic cache key
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Load .env
      uses: xom9ikk/dotenv@94dbc24d1aa2b127fbb296bd31a4c4039b16c23f # v2.1.0

    - name: Configure cargo
      shell: bash
      run: |
        # We do this since multiple jobs are run on the same CI build server,
        # and if multiple cargo build jobs run at max parallelism it ends up
        # slowing all builds down.
        echo "CARGO_BUILD_JOBS=6" >> $GITHUB_ENV

    # This action uses env vars for hash used in the key, therefore we keep it as last. 
    - uses: Swatinem/rust-cache@359a70e43a0bb8a13953b04a90f76428b4959bb6 # v2.2.0
      with:
        key: ${{ inputs.cache-key }}

