services:
  personalization:
    image: personalization:latest
    command: "--bind-to=0.0.0.0:3031"
    restart: "no"
    environment:
      XAYN_WEB_API__STORAGE__POSTGRES__BASE_URL:  "postgres://user:pw@postgres:5432/xayn"
      XAYN_WEB_API__STORAGE__ELASTIC__URL: "http://elasticsearch:9200/"
    ports:
      - 3031:3031
    depends_on:
      - elasticsearch
      - postgres
    networks:
      - internal
      - public

networks:
  # See other compose.db.yml
  internal:
    name: xayn-web-api_internal
  publisher:
    name: xayn-web-api_publisher
  public:
    name: xayn-web-api_public
