services:
  ingestion:
    image: xayn-web-api-ingestion:latest
    command: "--bind-to=0.0.0.0:3030"
    restart: "no"
    environment:
      XAYN_WEB_API__STORAGE__POSTGRES__BASE_URL:  "postgres://user:pw@postgres:5432/xayn"
      XAYN_WEB_API__STORAGE__ELASTIC__URL: "http://elasticsearch:9200/"
    ports:
      - "${HOST_PORT_SCOPE:-30}30:3030"
    depends_on:
      services_ready:
        condition: service_completed_successfully
    networks:
      - internal
      - publisher

networks:
  internal:
  publisher:
