services:
  postgres:
    image: postgres:15.2
    mem_limit: 1024m
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: xayn
    ports:
      - "${HOST_PORT_SCOPE:-30}54:5432"
    networks:
      - internal
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: elasticsearch:8.8.0
    mem_limit: 2048m
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "${HOST_PORT_SCOPE:-30}92:9200"
    networks:
      - internal
    healthcheck:
      test: curl --fail 'http://localhost:9200/_cluster/health'
      interval: 10s
      timeout: 5s
      retries: 5

  db_ready:
    image: debian:bookworm-slim
    command: echo dummy
    restart: "no"
    depends_on:
      elasticsearch:
        condition: service_healthy
      postgres:
        condition: service_healthy

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - "${HOST_PORT_SCOPE:-30}80:8080"
  #   networks:
  #     - internal

  # kibana:
  #   image: kibana:8.4.0
  #   restart: always
  #   ports:
  #     - "${HOST_PORT_SCOPE:-30}56:5601"
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - internal

networks:
  internal:
