FROM debian:12.4

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        ca-certificates python3.11 pipenv \
        ; \
    # rustls in aws
    update-ca-certificates

WORKDIR /app
COPY ./ ./

RUN pipenv install --deploy && pipenv run python -c 'import nltk; nltk.download("punkt")'

ENTRYPOINT ["/app/server.bin"]
