[package]
name = "async-bindgen-gen-dart"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.57"
handlebars = "4.3.1"
heck = "0.4.0"
once_cell = "1.12.0"
regex = "1.5.6"
serde = { version = "1.0.137", features = ["derive"] }
structopt = "0.3.26"

[dev-dependencies]
itertools = "0.10.3"
