[package]
name = "xayn-summarizer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
ndarray = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
unicode-segmentation = "^1.10.1"
