[package]
name = "async-bindgen"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = "Apache-2.0"

[dependencies]
async-bindgen-derive = { path = "../async-bindgen-derive" }
once_cell = { workspace = true }
static_assertions = "1.1.0"
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread"] }
xayn-dart-api-dl = "0.3.0"
