[package]
name = "async-bindgen"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
async-bindgen-derive = { path = "../async-bindgen-derive" }
once_cell = "1.13.1"
static_assertions = "1.1.0"
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["rt", "rt-multi-thread"], default-features = false }
xayn-dart-api-dl = "0.3.0"
