name: async_bindgen_dart_utils
description: A starting point for Dart libraries or applications.
version: 0.1.0+replace.with.version
publish_to: https://xayn.jfrog.io/artifactory/api/pub/dart.xayn.private

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
