name: async_bindgen_dart_utils
description: A starting point for Dart libraries or applications.
version: 0.1.0+replace.with.semver.metadata.marker
publish_to: https://xayn.jfrog.io/artifactory/api/pub/dart.yellow.private

environment:
  sdk: '>=2.17.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
