[package]
name = "xayn-discovery-engine-tooling"
version = "0.1.0"
license = "AGPL-3.0-only"
edition = "2021"

[[bin]]
name = "newscatcher"
path = "bin/newscatcher.rs"

[[bin]]
name = "clean_sources"
path = "bin/clean_sources.rs"

[dependencies]
anyhow = "1.0.57"
csv = "1.1.6"
serde_json = "1.0.81"
serde_path_to_error = "0.1.7"
tokio = { version = "1.19.2", features = ["fs"] }
xayn-discovery-engine-providers = { path = "../providers" }
