[package]
name = "xayn-discovery-engine-tooling"
version = "0.1.0"
license = "AGPL-3.0-only"
edition = "2021"

[[bin]]
name = "newscatcher"
path = "bin/newscatcher.rs"

[[bin]]
name = "clean_sources"
path = "bin/clean_sources.rs"

[[bin]]
name = "discovery_engine"
path = "bin/discovery_engine.rs"

[dependencies]
anyhow = "1.0.59"
clap = { version = "3.2.16", features = ["derive"] }
csv = "1.1.6"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
tokio = { version = "1.20.1", features = ["fs"] }
url = "2.2.2"
xayn-discovery-engine-ai = { path = "../ai/ai" }
xayn-discovery-engine-core = { path = "../core" }
xayn-discovery-engine-providers = { path = "../providers" }
