[package]
name = "tooling"
version = "0.1.0"
license = "AGPL-3.0-only"
edition = "2021"

[dependencies]
anyhow = "1.0.55"
csv = "1.1.6"
serde_json = "1.0.79"
tokio = { version = "1.17.0", features = ["full"] }
url = "2.2.2"
xayn-discovery-engine-providers = { path = "../providers" }
