[package]
name = "tooling"
version = "0.1.0"
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "newscatcher"
path = "bin/newscatcher.rs"

[dependencies]
anyhow = "1.0.55"
serde_json = "1.0.79"
serde_path_to_error = "0.1"
tokio = { version = "1.17.0", features = ["full"] }
xayn-discovery-engine-providers = { path = "../providers" }
