[package]
name = "xayn-discovery-engine-core"
version = "0.1.0"
license = "AGPL-3.0-only"
edition = "2018"

[dependencies]
async-trait = "0.1.52"
bincode = "1.3.3"
derivative = "2.2.0"
derive_more = { version = "0.99.17", default-features = false, features = ["display", "from"] }
displaydoc = "0.2.3"
rand = "0.8.4"
rand_distr = "0.4.2"
serde = { version = "1.0.130", features = ["derive"] }
thiserror = "1.0.30"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
xayn-ai = { git = "https://github.com/xaynetwork/xayn_ai", branch = "master" }

[dev-dependencies]
claim = "0.5.0"
float-cmp = "0.9.0"
mockall = "0.11.0"
