[package]
name = "xayn-discovery-engine-core"
version = "0.1.0"
license = "AGPL-3.0-only"
edition = "2018"

[dependencies]
async-trait = "0.1.52"
bincode = "1.3.3"
chrono = { version = "0.4.19", default-features = false, features = ["serde"] }
derivative = "2.2.0"
derive_more = { version = "0.99.17", default-features = false, features = ["display", "from"] }
displaydoc = "0.2.3"
figment = { version = "0.10.6", default-features = false, features = ["json"] }
futures = { version = "0.3.21", default-features = false, features = ["alloc"] }
kodama = "0.2.3"
rand = "0.8.5"
rand_distr = "0.4.3"
rayon = "1.5.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_repr = "0.1.7"
thiserror = "1.0.30"
tokio = { version = "1.17.0", default-features = false, features = ["sync"] }
tracing = "0.1.31"
url = { version = "2.2.2", features = ["serde"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
xayn-ai = { git = "https://github.com/xaynetwork/xayn_ai", branch = "TY-2467-cosine-similarity" }
xayn-discovery-engine-providers = { path = "../providers" }

[dev-dependencies]
claim = "0.5.0"
float-cmp = "0.9.0"
itertools = "0.10.3"
mockall = "0.11.0"
serde_json = "1.0.79"
tokio = { version = "1.17.0", default-features = false, features = ["macros", "rt", "sync"] }
