[package]
name = "xayn-discovery-engine-core"
version = "0.1.0"
edition = "2018"
authors = ["Xayn Engineering <engineering@xaynet.dev>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
