name: Dart checks

on:
  workflow_call:

jobs:
  dart-format:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v4
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Setup the dart CI.
        uses: ./.github/actions/setup-job-docker
        with:
          dart: true

      - name: Check formatting
        run: just dart-fmt

  dart-analyze:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v4
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Setup the rust/dart CI.
        uses: ./.github/actions/setup-job-docker
        with:
          dart: true
          rust: true

      - name: Analyze code
        run: just dart-check

  dart-test:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v4
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Setup the rust/dart CI.
        uses: ./.github/actions/setup-job-docker
        with:
          dart: true
          rust: true

      - name: Run tests without storage
        run: just dart-test

      - name: Run tests with storage
        run: XAYN_DE_FEATURES=storage just dart-test

  dart-doc:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v4
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Setup the dart CI.
        uses: ./.github/actions/setup-job-docker
        with:
          dart: true
          rust: true

      - name: Check documentation
        run: just dart-check-doc
