name: Rust checks

on:
  workflow_call:

jobs:
  cargo-format:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v8
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Setup the CI.
        uses: ./.github/actions/setup-job-docker

      - name: cargo fmt
        run: just rust-fmt

  cargo-clippy:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v8
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Setup the rust CI.
        uses: ./.github/actions/setup-job-docker

      - name: rust check
        run: just rust-check

  cargo-test:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v8
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Setup the rust CI.
        uses: ./.github/actions/setup-job-docker

      - name: Download test assets
        run: just download-assets

      - name: Run tests
        run: just rust-test

  cargo-doc:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v8
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Setup the rust CI.
        uses: ./.github/actions/setup-job-docker

      - name: cargo doc
        run: just rust-check-doc
