name: Rust checks

on:
  workflow_call:

jobs:
  cargo-format:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v9
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Setup the CI.
        uses: ./.github/actions/setup-job-docker

      - name: cargo fmt
        run: just rust-fmt

  cargo-clippy:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v9
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Setup the rust CI.
        uses: ./.github/actions/setup-job-docker

      - name: rust check
        run: just rust-check

  cargo-test:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v9
    timeout-minutes: 20
    services:
      elasticsearch:
        image: elasticsearch:8.5.3
        env:
          - discovery.type=single-node
          - xpack.security.enabled=false
        options: >-
          --health-cmd curl -sf 'localhost:9200/_cluster/health'
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres:
        image: postgres
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pw
          POSTGRES_DB: xayn
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Setup the rust CI.
        uses: ./.github/actions/setup-job-docker

      - name: Download test assets
        run: just download-assets

      - name: Run tests
        run: just rust-test

  cargo-doc:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v9
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Setup the rust CI.
        uses: ./.github/actions/setup-job-docker

      - name: cargo doc
        run: just rust-check-doc
