name: Rust checks

on:
  workflow_call:

jobs:
  cargo-format:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v4
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Setup the CI.
        uses: ./.github/actions/setup-job-docker
        with:
          rust: true

      - name: cargo fmt
        run: just rust-fmt

  cargo-clippy:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v4
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Setup the rust CI.
        uses: ./.github/actions/setup-job-docker
        with:
          rust: true

      - name: rust check
        run: |
          just rust-check
          XAYN_DE_FEATURES=storage just rust-check

  cargo-test:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v4
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Setup the rust CI.
        uses: ./.github/actions/setup-job-docker
        with:
          rust: true

      - name: Run tests
        run: |
          env
          just download-assets
          just rust-test
          XAYN_DE_FEATURES=storage just rust-test

  cargo-doc:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v4
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Setup the rust CI.
        uses: ./.github/actions/setup-job-docker
        with:
          rust: true

      - name: cargo doc
        run: |
          just rust-check-doc
