name: Rust checks

on:
  workflow_call:
    secrets:
      AWS_OIDC_ROLE:
        required: true

jobs:
  cargo-format:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v13
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: Setup the CI.
        uses: ./.github/actions/setup-job-docker

      - name: cargo fmt
        run: just rust-fmt

  cargo-clippy:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v13
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: Setup the rust CI.
        uses: ./.github/actions/setup-job-docker

      - name: rust check
        run: just rust-check

  cargo-doc:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v13
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: Setup the rust CI.
        uses: ./.github/actions/setup-job-docker

      - name: cargo doc
        run: just rust-check-doc
