name: Dart checks

on:
  workflow_call:

jobs:
  dart-format:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v5
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Setup the dart CI.
        uses: ./.github/actions/setup-job-docker
        with:
          dart: true

      - name: Check formatting
        run: just dart-fmt

  dart-analyze:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v5
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Setup the rust/dart CI.
        uses: ./.github/actions/setup-job-docker
        with:
          dart: true
          rust: true

      - name: Analyze code
        run: just dart-check

  dart-test:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v5
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Setup the rust/dart CI.
        uses: ./.github/actions/setup-job-docker
        with:
          dart: true
          rust: true

      - name: Run tests without storage
        run: XAYN_DE_FEATURES="" just dart-test

      - name: Run tests with storage
        run: XAYN_DE_FEATURES=storage just dart-test

  dart-doc:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v5
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Setup the dart CI.
        uses: ./.github/actions/setup-job-docker
        with:
          dart: true
          rust: true

      - name: Check documentation
        run: just dart-check-doc
