name: Flutter checks

on:
  workflow_call:

jobs:
  flutter-analyze:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v5
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Setup the CI
        uses: ./.github/actions/setup-job-docker
        with:
          rust: true

      - name: Analyze code
        run: just flutter-check

  flutter-test:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v5
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Setup the CI
        uses: ./.github/actions/setup-job-docker
        with:
          rust: true

      - name: Run tests
        run: just flutter-test
