name: Build flutter example

on:
  workflow_call:
    inputs:
      artifact-dir-base-ios:
        description: The base name of artifact directory (without the target suffix)
        required: true
        type: string

permissions:
  contents: read

jobs:
  flutter-build-example-ios:
    runs-on: hetzner-mac-pm
    timeout-minutes: 30
    steps:
      - name: Clean up workspace
        shell: bash
        run: rm -rf *

      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Setup the CI.
        uses: ./.github/actions/setup-job-macos
        with:
          flutter: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifacts
        id: artifacts
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # v3.0.0
        with:
          path: ${{ runner.temp }}/artifacts/

      - name: Copy artifacts
        working-directory: ${{ steps.artifacts.outputs.download-path }}
        run: cp -R ${{ inputs.artifact-dir-base-ios }}-*/* ${{ github.workspace }}/${{ env.FLUTTER_WORKSPACE }}/ios

      - name: Build flutter example
        run: just flutter-build ios --no-codesign

  flutter-build-example-android:
    # The reason we don't need the Android libraries here is that, for Android, we have
    # a dynamic library that is loaded at runtime, while for iOS we have a static library
    # that needs to exist during the linking process.
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v5
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Setup the CI.
        uses: ./.github/actions/setup-job-docker
        with:
          rust: true

      - name: Build flutter example
        run: just flutter-build apk
