name: Build iOS library

on:
  workflow_call:
    inputs:
      production:
        description: Builds iOS libraries for production release (with additional optimizations)
        default: false
        required: false
        type: boolean
    outputs:
      artifact-dir-base:
        description: The base name of artifact directory (without the target suffix)
        value: ${{ jobs.build-ios-libs.outputs.artifact-dir-base }}

jobs:
  build-ios-libs:
    runs-on: hetzner-mac-pm
    timeout-minutes: 60
    strategy:
      matrix:
        target: ["aarch64-apple-ios", "x86_64-apple-ios"]
    outputs:
      artifact-dir-base: ${{ steps.build.outputs.artifact-dir-base }}
    steps:
      - name: Clean up workspace
        shell: bash
        run: rm -rf *

      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Setup the rust CI
        uses: ./.github/actions/setup-job-macos
        with:
          rust-target: ${{ matrix.target }}
          cache-key: ${{ matrix.target }}-${{ inputs.production }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build iOS library ${{ matrix.target }}
        id: build
        run: |
          ARTIFACT_DIR_BASE=${{ github.job }}
          if ${{ inputs.production }}; then
            just compile-ios-ci ${{ matrix.target }} --prod
            ARTIFACT_DIR_BASE+="-production"
          else
            just compile-ios-ci ${{ matrix.target }}
          fi
          echo "::set-output name=artifact-dir-base::$ARTIFACT_DIR_BASE"

      - name: Prepare lib for upload
        id: lib
        run: |
          BASE=${{ env.RUST_WORKSPACE }}/target/${{ matrix.target }}/release/${{ env.IOS_LIB_BASE }}
          SRC=${BASE}.a
          DEST=${BASE}_${{ matrix.target }}.a
          mv $SRC $DEST
          echo "::set-output name=path::$DEST"

      - name: Upload library artifacts
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          name: ${{ steps.build.outputs.artifact-dir-base }}-${{ matrix.target }}-${{ github.sha }}
          retention-days: 1
          if-no-files-found: error
          path: ${{ steps.lib.outputs.path }}
