name: Rust checks

on:
  workflow_call:

jobs:
  cargo-format:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v5
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Setup the CI.
        uses: ./.github/actions/setup-job-docker
        with:
          rust: true

      - name: cargo fmt
        run: just rust-fmt

  cargo-clippy:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v5
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Setup the rust CI.
        uses: ./.github/actions/setup-job-docker
        with:
          rust: true

      - name: rust check
        run: just rust-check

  cargo-test:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v5
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Setup the rust CI.
        uses: ./.github/actions/setup-job-docker
        with:
          rust: true

      - name: Download test assets
        run: just download-assets

      - name: Run tests
        run: just rust-test

  cargo-doc:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v5
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Setup the rust CI.
        uses: ./.github/actions/setup-job-docker
        with:
          rust: true

      - name: cargo doc
        run: |
          just rust-check-doc
