name: Build Android library

on:
  workflow_call:
    inputs:
      production:
        description: Builds android libraries for production release (with additional optimizations)
        default: false
        required: false
        type: boolean
    outputs:
      artifact-dir-base:
        description: The base name of artifact directory (without the target suffix)
        value: ${{ jobs.build-android-libs.outputs.artifact-dir-base }}

jobs:
  build-android-libs:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v4
    timeout-minutes: 45
    strategy:
      matrix:
        target: [
          "aarch64-linux-android",
          "armv7-linux-androideabi",
          "x86_64-linux-android",
          "i686-linux-android",
        ]
    outputs:
      artifact-dir-base: ${{ steps.build.outputs.artifact-dir-base }}
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Setup the rust CI.
        uses: ./.github/actions/setup-job-docker
        with:
          rust: true
          cache-key: ${{ matrix.target }}-${{ inputs.production }}

      - name: Build Android library
        id: build
        run: |
          ARTIFACT_DIR_BASE=${{ github.job }}
          if ${{ inputs.production }}; then
            XAYN_DE_FEATURES="" just compile-android-ci "${{ matrix.target }}" --prod
            ARTIFACT_DIR_BASE="${ARTIFACT_DIR_BASE}-production"
          else
            XAYN_DE_FEATURES="" just compile-android-ci "${{ matrix.target }}"
          fi
          echo "::set-output name=artifact-dir-base::$ARTIFACT_DIR_BASE"

      - name: Check for malformed builds
        run: |
          just check-android-so

      - name: Upload library artifacts
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3.1.0
        with:
          name: ${{ steps.build.outputs.artifact-dir-base }}-${{ matrix.target }}-${{ github.sha }}
          retention-days: 1
          if-no-files-found: error
          path: ${{ env.FLUTTER_WORKSPACE }}/android/src/main/jniLibs
