name: Bors CI

on:
  push:
    branches:
      - '_bors_staging'
      - '_bors_trying'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  rust-checks:
    uses: ./.github/workflows/_reusable.rust.yml

  dart-checks:
    uses: ./.github/workflows/_reusable.dart.yml

  flutter-checks:
    uses: ./.github/workflows/_reusable.flutter.yml

  build-ios-libs:
    uses: ./.github/workflows/_reusable.build-ios.yml

  build-android-libs:
    uses: ./.github/workflows/_reusable.build-android.yml

  build-flutter-example:
    needs: build-ios-libs
    uses: ./.github/workflows/_reusable.build-flutter-example.yml
    with:
      artifact-dir-base-ios: ${{ needs.build-ios-libs.outputs.artifact-dir-base }}

  ci-ok:
    needs:
      - rust-checks
      - dart-checks
      - flutter-checks
      - build-ios-libs
      - build-android-libs
      - build-flutter-example
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v1
    timeout-minutes: 5
    if: ${{ always() }}
    steps:
      - name: CI OK Testing
        shell: bash
        run: |
          if [[
            "${{ needs.rust-checks.result }}" == "success" &&
            "${{ needs.dart-checks.result }}" == "success" &&
            "${{ needs.flutter-checks.result }}" == "success" &&
            "${{ needs.build-ios-libs.result }}" == "success" &&
            "${{ needs.build-android-libs.result }}" == "success" &&
            "${{ needs.build-flutter-example.result }}" == "success"
          ]]; then
            exit 0
          else
            exit 1
          fi
