name: Bors CI

on:
  push:
    branches:
      - '_bors_staging'
      - '_bors_trying'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  rust-checks:
    uses: ./.github/workflows/_reusable.rust.yml

  ci-ok:
    needs: rust-checks
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v6
    timeout-minutes: 5
    if: ${{ always() }}
    steps:
      - name: CI OK Testing
        shell: bash
        run: |
          if [[
            "${{ needs.rust-checks.result }}" == "success"
          ]]; then
            exit 0
          else
            exit 1
          fi
