name: Build docker ci image

on:
  workflow_dispatch:
    inputs:
      docker_push:
        required: true
        type: boolean
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  image_name: xaynetci/yellow

jobs:
  build-docker-image:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325 # v2.2.1

      - name: Determine rust version
        shell: bash
        run: |
          set -eux
          RUST_VERSION=$(perl -ne 'print $1 if /channel = \"(.*)\"/' discovery_engine_core/rust-toolchain.toml)
          echo "rust_version=${RUST_VERSION}" >> $GITHUB_ENV

      - name: Determine image tag
        run: |
          IMAGE_TAG="$(git rev-parse --short "$GITHUB_SHA")"
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: docker build
        shell: bash
        run: |
          set -eux
          source .env
          docker build \
            --build-arg rust_version="${{ env.rust_version }}" \
            --build-arg rust_nightly_version="${RUST_NIGHTLY}" \
            --build-arg just_version="${JUST_VERSION}" \
            --build-arg cargo_sort_version="${CARGO_SORT_VERSION}" \
            --tag "${{ env.image_name }}:${{ env.image_tag }}" \
            - < .github/docker/Dockerfile.ci-image

      - name: Login to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        if: ${{ inputs.docker_push }}
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: docker push
        if: ${{ inputs.docker_push }}
        run: docker push "${{ env.image_name }}:${{ env.image_tag }}"
