name: CI

on:
  merge_group:
  push:
    branches-ignore:
      - 'main'
      - '_bors*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  rust-checks:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/_reusable.rust.yml
    secrets:
      AWS_OIDC_ROLE: ${{ secrets.AWS_OIDC_ROLE }}

  open-api:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v15
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Validate openapi
        run: just validate-openapi

  copyright:
    if: ${{ always() }}
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v15
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Check copyright
        run: .github/scripts/copyright.sh

  ci-ok:
    if: always()
    needs:
      - rust-checks
      - open-api
      - copyright
    runs-on: ubuntu-22.04
    steps:
      - name: All jobs in this workflow succeeded
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}

