name: CI
on:
  push:
    branches-ignore:
      - 'main'
      - '_bors*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dev-ci:
    uses: ./.github/workflows/ci_reusable_wf.yml

  ci-ok:
    needs: dev-ci
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v1
    timeout-minutes: 5
    steps:
      - name: CI OK Testing
        run: |
          if ( ${{needs.dev-ci.outputs.wf-result == 'success'}} )
          then
            exit 0
          else
            exit 1
          fi
