name: Dev CI

on:
  push:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  DART_VERSION: '2.14.4'

jobs:
  dart-format:
    name: dart-format
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # v2.3.5

      - name: Install dart
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d # v1.3
        with:
          sdk: ${{ env.DART_VERSION }}

      - name: Check formatting
        working-directory: discovery_engine
        run: dart format --output=none --set-exit-if-changed .

  dart-analyze:
    name: dart-analyze
    needs: dart-format
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # v2.3.5

      - name: Install dart
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d # v1.3
        with:
          sdk: ${{ env.DART_VERSION }}

      - name: Install dependencies
        working-directory: discovery_engine
        run: dart pub get

      - name: Other Dart code generation
        working-directory: ${{ env.DART_WORKSPACE }}
        run: dart run build_runner build

      - name: Analyze code
        working-directory: discovery_engine
        run: dart analyze --fatal-infos

  dart-test:
    name: dart-test
    needs: dart-analyze
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # v2.3.5

      - name: Install dart
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d # v1.3
        with:
          sdk: ${{ env.DART_VERSION }}

      - name: Install dependencies
        working-directory: discovery_engine
        run: dart pub get
 
      - name: Other Dart code generation
        working-directory: ${{ env.DART_WORKSPACE }}
        run: dart run build_runner build

      - name: Run tests
        working-directory: discovery_engine
        run: dart test

  dart-doc:
    name: dart-doc
    needs: dart-test
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # v2.3.5

      - name: Install dart
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d # v1.3
        with:
          sdk: ${{ env.DART_VERSION }}

      - name: Install dartdoc
        working-directory: discovery_engine
        run: dart pub global activate dartdoc

      - name: Other Dart code generation
        working-directory: ${{ env.DART_WORKSPACE }}
        run: dart run build_runner build

      - name: Check documentation
        working-directory: discovery_engine
        run: dart pub global run dartdoc:dartdoc --no-generate-docs --no-quiet

  # this is an helper that needs all the real leafs of the workflow.
  # It makes easier notify_main_failure because we only need to check
  # for this job
  ci-ok:
    name: ci-ok
    needs:
      - dart-test
    runs-on: ubuntu-20.04
    steps:
      - name: Nothing to do
        run: echo "Helper job nothing to do"

  notify-main-failure:
    name: notify-main-failure
    needs: ci-ok
    # always() allows to run even if ci-ok is not successful
    # we only want this to run on the main branch
    if: always() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    steps:
      - name: Notify failure
        if: needs.ci-ok.result != 'success'
        uses: 8398a7/action-slack@c84a35cfa82a01f3733a3cbf5d5260123e55c2f9 # v3.9.2
        with:
          status: custom
          fields: workflow, repo
          custom_payload: |
            {
              attachments: [{
                title: 'Main CI failed :warning:',
                color: 'danger',
                text: `CI: ${process.env.AS_WORKFLOW}\nRepository: ${process.env.AS_REPO}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
