name: CI
on:
  push:
    branches-ignore:
      - 'main'
      - '_bors*'
    paths:
      - '.github/workflows/ci*'
      - 'discovery_engine/**'
      - 'discovery_engine_core/**'
      - 'discovery_engine_flutter/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dev-ci:
    uses: xaynetwork/xayn_discovery_engine/.github/workflows/ci_reusable_wf.yml@DEVOPS671_adding_bors_reusable_wf
  
  ci-ok:
    name: ci-ok
    needs: [dev-ci]
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: CI OK Testing
        run: |
          echo ${{needs.dev-ci.outputs.wf-value}}
          echo ${{needs.dev-ci.outputs.wf-result}}
          if ( ${{needs.dev-ci.outputs.wf-value == 'success'}} )
          then
            exit 0
          else
            exit 1
          fi
          
        
