name: Bors CI

# on:
#   push:
#     branches:
#       - '_bors_staging'
#       - '_bors_trying'

on:
  push:
    branches-ignore:
      - 'main'
      - '_bors*'

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

permissions:
  contents: read

jobs:
  dev-ci:
    uses: ./.github/workflows/ci_reusable_wf.yml

  build-ios-libs:
    uses: ./.github/workflows/ci_build_ios.yml

  build-android-libs:
    uses: ./.github/workflows/ci_build_android.yml

  build-flutter-example:
    needs: build-ios-libs
    uses: ./.github/workflows/ci_flutter_example.yml
    with:
      artifact-dir-base-ios: ${{ needs.build-ios-libs.outputs.artifact-dir-base }}

  ci-ok:
    needs: [dev-ci, build-ios-libs, build-android-libs, build-flutter-example]
    runs-on: azure-vm
    timeout-minutes: 5
    if: always()
    steps:
      - name: CI OK Testing
        run: |
          if [[
            "${{ needs.dev-ci.outputs.wf-result }}" == "success" &&
            "${{ needs.build-ios-libs.result }}" == "success" &&
            "${{ needs.build-android-libs.result }}" == "success" &&
            "${{ needs.build-flutter-example.result }}" == "success"
          ]]; then
            exit 0
          else
            exit 1
          fi
