name: Bors CI
on:
  push:
    branches:
      - '_bors_staging'
      - '_bors_trying'
    paths:
      - '.github/workflows/ci*'
      - 'discovery_engine/**'
      - 'discovery_engine_core/**'
      - 'discovery_engine_flutter/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dev-ci:
    uses: xaynetwork/xayn_discovery_engine/.github/workflows/ci_reusable_wf.yml@updated-lock-file-because-of-upated-git-deps

  ci-ok:
    name: ci-ok
    needs: [dev-ci]
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: CI OK Testing
        run: |
          if ( ${{needs.dev-ci.outputs.wf-result == 'success'}} )
          then
            exit 0
          else
            exit 1
          fi
