name: Build iOS library

on:
  workflow_call:
    outputs:
      artifact-dir-base:
        description: The base name of artifact directory (without the target suffix)
        value: ${{ jobs.build-ios-libs.outputs.artifact-dir-base }}

jobs:
  build-ios-libs:
    runs-on: macos-11
    timeout-minutes: 35
    strategy:
      matrix:
        target: ["aarch64-apple-ios", "x86_64-apple-ios"]
    env:
      ARTIFACT_DIR_BASE: ${{ github.job }}
    outputs:
      artifact-dir-base: ${{ env.ARTIFACT_DIR_BASE }}
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Setup the rust CI
        uses: ./.github/actions/setup-job
        with:
          rust: true
          rust-target: ${{ matrix.target }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build iOS library ${{ matrix.target }}
        run: just compile-ios ${{ matrix.target }}

      - name: Prepare lib for upload
        id: lib
        run: |
          BASE=${{ env.RUST_WORKSPACE }}/target/${{ matrix.target }}/release/${{ env.IOS_LIB_BASE }}
          SRC=${BASE}.a
          DEST=${BASE}_${{ matrix.target }}.a
          mv $SRC $DEST
          echo "::set-output name=path::$DEST"

      - name: Upload library artifacts
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          name: ${{ env.ARTIFACT_DIR_BASE }}-${{ matrix.target }}-${{ github.sha }}
          retention-days: 1
          if-no-files-found: error
          path: ${{ steps.lib.outputs.path }}
