name: Dart CI

on:
  push:
    paths:
      - '.github/workflows/dart_ci.yml'
      - 'discovery_engine/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  DART_VERSION: '2.14.4'
  DART_WORKSPACE: ${{ github.workspace }}/discovery_engine

jobs:
  dart-format:
    name: dart-format
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Install dart
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d # v1.3
        with:
          sdk: ${{ env.DART_VERSION }}

      - name: Check formatting
        working-directory: ${{ env.DART_WORKSPACE }}
        run: dart format --output=none --set-exit-if-changed .

  dart-analyze:
    name: dart-analyze
    needs: dart-format
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Install dart
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d # v1.3
        with:
          sdk: ${{ env.DART_VERSION }}

      - name: Install dependencies
        working-directory: ${{ env.DART_WORKSPACE }}
        run: dart pub get

      - name: Install dependencies for the example
        working-directory: ${{ env.DART_WORKSPACE }}/example
        run: dart pub get

      - name: Other Dart code generation
        working-directory: ${{ env.DART_WORKSPACE }}
        run: dart run build_runner build

      - name: Analyze code
        working-directory: ${{ env.DART_WORKSPACE }}
        run: dart analyze --fatal-infos

  dart-test:
    name: dart-test
    needs: dart-analyze
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Install dart
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d # v1.3
        with:
          sdk: ${{ env.DART_VERSION }}

      - name: Install dependencies
        working-directory: ${{ env.DART_WORKSPACE }}
        run: dart pub get

      - name: Other Dart code generation
        working-directory: ${{ env.DART_WORKSPACE }}
        run: dart run build_runner build

      - name: Run tests
        working-directory: ${{ env.DART_WORKSPACE }}
        run: dart test

  dart-doc:
    name: dart-doc
    needs: dart-test
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Install dart
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d # v1.3
        with:
          sdk: ${{ env.DART_VERSION }}

      - name: Install dartdoc
        working-directory: ${{ env.DART_WORKSPACE }}
        run: dart pub global activate dartdoc

      - name: Other Dart code generation
        working-directory: ${{ env.DART_WORKSPACE }}
        run: dart run build_runner build

      - name: Check documentation
        working-directory: ${{ env.DART_WORKSPACE }}
        run: dart pub global run dartdoc:dartdoc --no-generate-docs --no-quiet

  # this is an helper that needs all the real leafs of the workflow.
  # It makes easier notify_main_failure because we only need to check
  # for this job
  ci-ok:
    name: ci-ok
    needs:
      - dart-doc
    runs-on: ubuntu-20.04
    steps:
        run: echo "Helper job"
