name: Dart CI

on:
  push:
    paths:
      - '.github/workflows/dart_ci.yml'
      - 'discovery_engine/**'
      - 'discovery_engine_core/**'
      - 'job_runner.sh'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  DART_VERSION: '2.14.4'
  DART_WORKSPACE: ${{ github.workspace }}/discovery_engine
  RUST_WORKSPACE: ${{ github.workspace }}/discovery_engine_core


jobs:
  dart-format:
    name: dart-format
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Install dart
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d # v1.3
        with:
          sdk: ${{ env.DART_VERSION }}

      - name: Check formatting
        working-directory: ${{ env.DART_WORKSPACE }}
        run: dart format --output=none --set-exit-if-changed .

  dart-analyze:
    name: dart-analyze
    needs: dart-format
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Install dart
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d # v1.3
        with:
          sdk: ${{ env.DART_VERSION }}

      - name: Install rust toolchain
        working-directory: ${{ env.RUST_WORKSPACE }}
        run: rustup show

      - uses: Swatinem/rust-cache@d12701459954fec471b2d34cdf7ea3374b026383 # v1
        with:
          working-directory: ${{ env.RUST_WORKSPACE }}

      - name: Install libclang-10-dev
        # required by ffigen
        run: sudo apt-get install libclang-10-dev

      - name: Install async-bindgen-gen-dart
        run: |
          cargo install \
            --git https://github.com/xaynetwork/xayn_async_bindgen.git \
            async-bindgen-gen-dart \
            "$@"

      - name: Install dependencies
        working-directory: ${{ env.DART_WORKSPACE }}
        run: dart pub get

      - name: Install dependencies for the example
        working-directory: ${{ env.DART_WORKSPACE }}/example
        run: dart pub get

      - name: Other Dart code generation
        working-directory: ${{ env.DART_WORKSPACE }}
        run: dart run build_runner build

      - name: Generate rust FFI glue
        run: |
          cd "$RUST_WORKSPACE"
          # Codegen order workaround
          cargo check --quiet 2>/dev/null || :
          # Run cbindgen and build the shared object
          cargo check
          # Generate dart bindings
          cd "$DART_WORKSPACE"
          dart run ffigen --config ffigen.yaml
          cd "$RUST_WORKSPACE"
          "${CARGO_INSTALL_ROOT:-${CARGO_HOME:-$HOME/.cargo}}/bin/async-bindgen-gen-dart" \
            --ffi-class XaynDiscoveryEngineBindingsFfi \
            --genesis ../discovery_engine/lib/src/ffi/genesis.ffigen.dart

      - name: Analyze code
        working-directory: ${{ env.DART_WORKSPACE }}
        run: dart analyze --fatal-infos

  dart-test:
    name: dart-test
    needs: dart-analyze
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Install dart
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d # v1.3
        with:
          sdk: ${{ env.DART_VERSION }}

      - name: Install rust toolchain
        working-directory: ${{ env.RUST_WORKSPACE }}
        run: rustup show

      - uses: Swatinem/rust-cache@d12701459954fec471b2d34cdf7ea3374b026383 # v1
        with:
          working-directory: ${{ env.RUST_WORKSPACE }}

      - name: Install async-bindgen-gen-dart
        run: |
          cargo install \
            --git https://github.com/xaynetwork/xayn_async_bindgen.git \
            async-bindgen-gen-dart \
            "$@"

      - name: Install libclang-10-dev
        # required by ffigen
        run: sudo apt-get install libclang-10-dev

      - name: Install dependencies
        working-directory: ${{ env.DART_WORKSPACE }}
        run: dart pub get

      - name: Other Dart code generation
        working-directory: ${{ env.DART_WORKSPACE }}
        run: dart run build_runner build

      - name: Generate rust FFI
        run: |
          cd "$RUST_WORKSPACE"
          # Codegen order workaround
          cargo check --quiet 2>/dev/null || :
          # Run cbindgen and build the shared object
          cargo build
          # Generate dart bindings
          cd "$DART_WORKSPACE"
          dart run ffigen --config ffigen.yaml
          cd "$RUST_WORKSPACE"
          "${CARGO_INSTALL_ROOT:-${CARGO_HOME:-$HOME/.cargo}}/bin/async-bindgen-gen-dart" \
            --ffi-class XaynDiscoveryEngineBindingsFfi \
            --genesis ../discovery_engine/lib/src/ffi/genesis.ffigen.dart


      - name: Run tests
        working-directory: ${{ env.DART_WORKSPACE }}
        run: dart test

  dart-doc:
    name: dart-doc
    needs: dart-test
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Install dart
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d # v1.3
        with:
          sdk: ${{ env.DART_VERSION }}

      - name: Install dartdoc
        working-directory: ${{ env.DART_WORKSPACE }}
        run: dart pub global activate dartdoc

      - name: Other Dart code generation
        working-directory: ${{ env.DART_WORKSPACE }}
        run: dart run build_runner build

      - name: Check documentation
        working-directory: ${{ env.DART_WORKSPACE }}
        run: dart pub global run dartdoc:dartdoc --no-generate-docs --no-quiet

  # this is an helper that needs all the real leafs of the workflow.
  # It makes easier notify_main_failure because we only need to check
  # for this job
  ci-ok:
    name: ci-ok
    needs:
      - dart-test
    runs-on: ubuntu-20.04
    steps:
      - name: Nothing to do
        run: echo "Helper job nothing to do"

  notify-main-failure:
    name: notify-main-failure
    needs: ci-ok
    # always() allows to run even if ci-ok is not successful
    # we only want this to run on the main branch
    if: always() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    steps:
      - name: Notify failure
        if: needs.ci-ok.result != 'success'
        uses: 8398a7/action-slack@b17d9de8e9ed64b041e4fac845d6fdb2be6b9b04 # v3.11.0
        with:
          status: custom
          fields: workflow, repo
          custom_payload: |
            {
              attachments: [{
                title: 'Main CI failed :warning:',
                color: 'danger',
                text: `CI: ${process.env.AS_WORKFLOW}\nRepository: ${process.env.AS_REPO}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
