name: Generate Documentation

on:
  push:
    branches:
      - main
      - ET-3610_better_documentation
    paths:
      - 'web-api/openapi/**'
      - 'docs/**'
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup redocly
        run: npm i -g @redocly/cli@latest

      - name: Setup sphinx
        working-directory: ./docs
        run: pip install -r requirements.txt

      - name:  Generate all documentation
        working-directory: ./docs
        run: make build

      - name: Deploy generated docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html/
