name: Generate Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'web-api/openapi/**'
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

    - name: Generate front-office docs
      uses: seeebiii/redoc-cli-github-action@c9649b33918da5eb290b81cd03a943caea091540 # v10
      with:
        args: 'bundle web-api/openapi/front_office.yaml -o front_office.html'

    - name: Generate back-office docs
      uses: seeebiii/redoc-cli-github-action@c9649b33918da5eb290b81cd03a943caea091540 # v10
      with:
        args: 'bundle web-api/openapi/back_office.yaml -o back_office.html'

    - name: Deploy generated docs to GitHub Pages
      uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
