name: Generate Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'web-api/openapi/**'
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v14
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Generate front-office docs
        run: redocly build-docs web-api/openapi/front_office.yaml -o front_office.html

      - name: Generate back-office docs
        run: redocly build-docs web-api/openapi/back_office.yaml -o back_office.html

      - name: Deploy generated docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
