name: Ingestion Service Release

on:
  workflow_dispatch:
    inputs:
      tag:
        required: false
        description: a tag that will be used for identifying this version (xaynetci/xayn_discovery_ingestion_service:$TAG)

permissions:
  contents: read

env:
  DENY_WARNINGS: false

jobs:
  rust-build:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v5
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Setup job
        uses: ./.github/actions/setup-job-docker
        with:
          rust: true

      - name: Build artifacts
        run: just build-ingestion-service

      - name: Download assets
        run: just download-assets

      - name: Prepare temp directory
        working-directory: ${{ runner.temp }}
        run: |
          rm -rf ./ingestion-service
          mkdir -p ingestion-service/assets

      - name: Create archive
        working-directory: ${{ runner.temp }}
        run: |
          cp ${GITHUB_WORKSPACE}/${{ env.RUST_WORKSPACE }}/target/release/ingestion ./ingestion-service/ingestion
          cp ${GITHUB_WORKSPACE}/${{ env.RUST_WORKSPACE }}/web-api/Dockerfile.ingestion ./ingestion-service/Dockerfile
          cp ${GITHUB_WORKSPACE}/${{ env.RUST_WORKSPACE }}/assets/smbert_v0003/config.toml ./ingestion-service/assets/config.toml
          cp ${GITHUB_WORKSPACE}/${{ env.RUST_WORKSPACE }}/assets/smbert_v0003/vocab.txt ./ingestion-service/assets/vocab.txt
          cp ${GITHUB_WORKSPACE}/${{ env.RUST_WORKSPACE }}/assets/smbert_v0003/model.onnx ./ingestion-service/assets/model.onnx
          tar -cvf ingestion-service.tar ./ingestion-service

      - name: Upload archive
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3.1.0
        with:
          name: ingestion-service
          retention-days: 1
          if-no-files-found: error
          path: ${{ runner.temp }}/ingestion-service.tar

  docker-build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    needs: [rust-build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Download artifacts
        id: artifacts
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # v3.0.0
        with:
          name: ingestion-service

      - name: Create docker image
        run: |
          tar -xvf ingestion-service.tar
          cd ./ingestion-service
          TAG=${{ github.event.inputs.tag }}
          if [ -z "$TAG" ]; then
            TAG="branch-$(git rev-parse --abbrev-ref HEAD)"
            if [[ "${TAG}" == "branch-HEAD" ]]; then
              TAG="$(git rev-parse --short HEAD)"
            fi
          fi
          IMAGE_NAME="xaynetci/xayn_discovery_ingestion_service:$TAG"
          docker build -t "${IMAGE_NAME}" .
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
          echo "TAG=${TAG}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: docker push
        id: docker-push
        run: docker push "${IMAGE_NAME}"
