name: Integration Tests

on:
  push:
    branches: [ ET-3848-integrate-tests ]

jobs:
  integration-test:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v11
    timeout-minutes: 20
    env:
      INGESTION_URI: "https://127.0.0.1:3030/test_index"
      XAYN_INGESTION__NET__BIND_TO: "127.0.0.1:3030"
      PERSONALIZATION_URI: "http://127.0.1.1:3031"
      XAYN_PERSONALIZATION__NET__BIND_TO: "127.0.0.1:3031"
      XAYN_WEB_API__STORAGE__POSTGRES__BASE_URL: "postgresql://user:pw@postgres/xayn"
      XAYN_WEB_API__STORAGE__ELASTIC__URL: "http://elasticsearch:9200"
      XAYN_WEB_API__STORAGE__ELASTIC__INDEX_NAME: "test_index"
    services:
      elasticsearch:
        image: elasticsearch:8.5.3
        env:
          "discovery.type": "single-node"
          "xpack.security.enabled": "false"
        options: >-
          --health-cmd "curl --fail 'http://localhost:9200/_cluster/health'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres:
        image: postgres:15.1
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pw
          POSTGRES_DB: xayn
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: Download assets
        run: just download-assets

      - name: Prepare temp directory
        run: |
          cd web-api
          mkdir -p assets
          cp ${GITHUB_WORKSPACE}/assets/smbert_v0003/config.toml ./assets/config.toml
          cp ${GITHUB_WORKSPACE}/assets/smbert_v0003/vocab.txt ./assets/vocab.txt
          cp ${GITHUB_WORKSPACE}/assets/smbert_v0003/model.onnx ./assets/model.onnx

      - name: Compile binaries
        run: |
          cargo build -p xayn-web-api

      - name: Setup ES index
        run: |
          ./web-api/elastic-search/create_es_index.sh "$XAYN_WEB_API__STORAGE__ELASTIC__URL/$XAYN_WEB_API__STORAGE__ELASTIC__INDEX_NAME"

      - name: Build Ingestion
        run: |
          cargo run --release --bin ingestion -- &
          .github/scripts/wait_for_it.sh $XAYN_INGESTION__NET__BIND_TO -t 60 -- echo "Ingestion service is up and running"

      - name: Build Personalization
        run: |
          cargo run --release --bin personalization &
          .github/scripts/wait_for_it.sh $XAYN_PERSONALIZATION__NET__BIND_TO -t 60 -- echo "Personalization service is up and running"

     - name: Set up Python/ Pip cache
       uses: actions/setup-python@v4
       with:
         python-version: 3.9
         cache: 'pip'
     - name: Install dependencies
       run: pip install -r "discovery_engine_api_tests/requirements.txt"

     - name: Run pytest
       env:
         PYTHONPATH: cd discovery_engine_api_tests
       run: |
         cd discovery_engine_api_tests/tests
         cd tests
         pytest
