name: PR Label Assigner  

on:
  pull_request:
    types: [opened, converted_to_draft, ready_for_review]
  workflow_dispatch:

permissions: 
  pull-requests: write

jobs:
  draft_pr:
    if: (github.event.pull_request.draft == true)
    runs-on: ubuntu-20.04
    name: Add WIP label
    steps:
      - name: Add WIP Label
        uses: buildsville/add-remove-label@6008d7bd99d3baeb7c04033584e68f8ec80b198b # v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: work-in-progress
          type: add

      - name: Remove Ready for Review Label 
        uses: buildsville/add-remove-label@6008d7bd99d3baeb7c04033584e68f8ec80b198b # v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: ready-for-review
          type: remove

  ready_for_review_pr:
    if: (github.event.pull_request.draft == false)  
    runs-on: ubuntu-20.04
    name: Remove label
    steps:
      - name: Remove WIP Label 
        uses: buildsville/add-remove-label@6008d7bd99d3baeb7c04033584e68f8ec80b198b # v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: work-in-progress
          type: remove

      - name: Add Ready for Review Label
        uses: buildsville/add-remove-label@6008d7bd99d3baeb7c04033584e68f8ec80b198b # v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: ready-for-review
          type: add
