name: PR Label Assigner  

on:
  pull_request:
    types: [opened, converted_to_draft, ready_for_review]
  workflow_dispatch:

permissions: 
  pull-requests: write

jobs:
  draft_pr:
    if: (github.event.pull_request.draft == true)
    runs-on: ubuntu-22.04
    name: Add WIP label
    steps:
      - name: Add WIP Label
        uses: buildsville/add-remove-label@eeae411a9be2e173f2420e1644514edbecc4e835 # v2.0.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          labels: work-in-progress
          type: add

      - name: Remove Ready for Review Label 
        uses: buildsville/add-remove-label@eeae411a9be2e173f2420e1644514edbecc4e835 # v2.0.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          labels: ready-for-review
          type: remove

  ready_for_review_pr:
    if: (github.event.pull_request.draft == false)  
    runs-on: ubuntu-22.04
    name: Remove label
    steps:
      - name: Remove WIP Label 
        uses: buildsville/add-remove-label@eeae411a9be2e173f2420e1644514edbecc4e835 # v2.0.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          labels: work-in-progress
          type: remove

      - name: Add Ready for Review Label
        uses: buildsville/add-remove-label@eeae411a9be2e173f2420e1644514edbecc4e835 # v2.0.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          labels: ready-for-review
          type: add
