name: CI

on:
  push:
    branches-ignore:
      - 'main'
      - '_bors*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  selection:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v5
    outputs:
      rust: ${{ steps.filter.outputs.rust }}
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721 # v2.10.2
        id: filter
        with:
          filters: |
            rust: &rust
              - 'discovery_engine_core/**'
              - '.github/actions/setup-job-docker/*'
              - '.github/workflows/_reusable.rust.yml'
              - 'justfile'

  rust-checks:
    needs: selection
    if: ${{ needs.selection.outputs.rust  == 'true' }}
    uses: ./.github/workflows/_reusable.rust.yml

  copyright:
    if: ${{ always() }}
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v5
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Check copyright
        run: .github/scripts/copyright.sh
