name: CI

on:
  push:
    branches-ignore:
      - 'main'
      - '_bors*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  test:
    runs-on: hetzner-mac-pm
    steps:
      - run: echo $(uname -m)
      - shell: sh
        run: arch -arm64 echo $(uname -m)

  # build-ios-libs:
  #   uses: ./.github/workflows/_reusable.build-ios.yml


      # - uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721
      #   id: filter
      #   with:
      #     filters: |
      #       rust: &rust
      #         - 'discovery_engine_core/**'
      #         - '.github/workflows/ci*'
      #         - '.github/actions/setup-job-docker/*'
      #         - '.github/actions/setup-job/*'
      #         - 'justfile'
      #       dart: &dart
      #         - *rust
      #         - 'discovery_engine/**'
      #       flutter:
      #         - *rust
      #         - *dart
      #         - 'discovery_engine_flutter/**'

  # rust-checks:
  #   needs: selection
  #   if: ${{ needs.selection.outputs.rust  == 'true' }}
  #   uses: ./.github/workflows/_reusable.rust.yml

  # dart-checks:
  #   needs: selection
  #   if: ${{ needs.selection.outputs.dart  == 'true' }}
  #   uses: ./.github/workflows/_reusable.dart.yml

  # flutter-checks:
  #   needs: selection
  #   if: ${{ needs.selection.outputs.flutter  == 'true' }}
  #   uses: ./.github/workflows/_reusable.flutter.yml

  # copyright:
  #   if: ${{ always() }}
  #   runs-on: hetzner-pm
  #   container:
  #     image: xaynetci/yellow:v1
  #   timeout-minutes: 5
  #   steps:
  #     - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

  #     - name: Check copyright
  #       run: .github/scripts/copyright.sh
