name: CI

on:
  push:
    branches-ignore:
      - 'main'
      - '_bors*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  rust-checks:
    uses: ./.github/workflows/_reusable.rust.yml

  open-api:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v7
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0    
  
      - name: Validate openapi
        run: just validate-openapi

  copyright:
    if: ${{ always() }}
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v7
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Check copyright
        run: .github/scripts/copyright.sh
