name: CI

on:
  push:
    branches-ignore:
      - 'main'
      - '_bors*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  selection:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v4
    outputs:
      dart: ${{ steps.filter.outputs.dart }}
      rust: ${{ steps.filter.outputs.rust }}
      flutter: ${{ steps.filter.outputs.flutter }}
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721 # v2.10.2
        id: filter
        with:
          filters: |
            rust: &rust
              - 'discovery_engine_core/**'
              - '.github/workflows/ci*'
              - '.github/actions/setup-job-docker/*'
              - '.github/actions/setup-job/*'
              - 'justfile'
            dart: &dart
              - *rust
              - 'discovery_engine/**'
            flutter:
              - *rust
              - *dart
              - 'discovery_engine_flutter/**'

  rust-checks:
    needs: selection
    if: ${{ needs.selection.outputs.rust  == 'true' }}
    uses: ./.github/workflows/_reusable.rust.yml

  dart-checks:
    needs: selection
    if: ${{ needs.selection.outputs.dart  == 'true' }}
    uses: ./.github/workflows/_reusable.dart.yml

  flutter-checks:
    needs: selection
    if: ${{ needs.selection.outputs.flutter  == 'true' }}
    uses: ./.github/workflows/_reusable.flutter.yml

  copyright:
    if: ${{ always() }}
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v4
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Check copyright
        run: .github/scripts/copyright.sh
