name: CI

on:
  push:
    branches-ignore:
      - 'main'
      - '_bors*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  rust-checks:
    uses: ./.github/workflows/_reusable.rust.yml

  open-api:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v9
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
  
      - name: Validate openapi
        run: just validate-openapi

  copyright:
    if: ${{ always() }}
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v9
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Check copyright
        run: .github/scripts/copyright.sh
