name: CI

on:
  push:
    branches-ignore:
      - 'main'
      - '_bors*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  rust-checks:
    uses: ./.github/workflows/_reusable.rust.yml

  open-api:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0    
  
      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install spectral
        run: npm install -g @stoplight/spectral-cli

      - name: Install ruleset
        run: npm install @ibm-cloud/openapi-ruleset validator

      - name: Validate
        run: spectral lint web-api/openapi/*.yaml

  copyright:
    if: ${{ always() }}
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v6
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Check copyright
        run: .github/scripts/copyright.sh
