name: CI

on:
  push:
    branches-ignore:
      - 'main'
      - '_bors*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  rust-checks:
    uses: ./.github/workflows/_reusable.rust.yml

  open-api:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v8
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
  
      - name: Validate openapi
        run: just validate-openapi

  copyright:
    if: ${{ always() }}
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v8
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Check copyright
        run: .github/scripts/copyright.sh
