name: Release docker ci image

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  image_name: xaynetci/yellow
  release_tag: v5

jobs:
  release:
    runs-on: hetzner-pm
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        if: github.ref == 'refs/heads/main'
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Determine image tag
        run: |
          IMAGE_TAG="$(git rev-parse --short "$GITHUB_SHA")"
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: docker pull
        run: |
          docker pull "${{ env.image_name }}:${{ env.image_tag }}"
      
      - name: tag as release
        run: docker tag "${{ env.image_name }}:${{ env.image_tag }}" "${{ env.image_name }}:${{ env.release_tag }}"

      - name: docker push
        run: docker push "${{ env.image_name }}:${{ env.release_tag }}"
