name: Release-CI

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

permissions:
  contents: read

env:
  DART_WORKSPACE: ${{ github.workspace }}/discovery_engine
  FLUTTER_WORKSPACE: ${{ github.workspace }}/discovery_engine_flutter

jobs:
  release:
    name: release
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@3c9b0fc6f2d223b8450b02a0445f526350fc73e0 # v2.3.1
        with:
          key: ${{ secrets.SSH }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Setup job
        uses: ./.github/actions/setup-job
        with:
          dart: true
          rust: true

      - name: Generate Files
        shell: bash
        run: just dart-build

      - name: Configure Git
        shell: bash
        run: |
          git config --global user.email "ci@xayn.com"
          git config --global user.name "ci"

      - name: Copy Repository
        shell: bash
        run: .github/scripts/release.sh --do-push
