name: Rust CI

on:
  push:
    paths:
      - '.github/workflows/rust_ci.yml'
      - 'discovery_engine_core/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  RUST_STABLE: 1.55
  RUST_WORKSPACE: ${{ github.workspace }}/discovery_engine_core

jobs:
  cargo-format:
    name: cargo-format
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Install ${{ env.RUST_STABLE }} toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          profile: minimal
          toolchain: ${{ env.RUST_STABLE }}
          components: rustfmt
          default: true

      - uses: Swatinem/rust-cache@d12701459954fec471b2d34cdf7ea3374b026383 # v1

      - name: cargo fmt
        working-directory: ${{ env.RUST_WORKSPACE }}
        run: cargo fmt --all -- --check

  cargo-clippy:
    name: cargo-clippy
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Install ${{ env.RUST_STABLE }} toolchain
        id: rust-toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          profile: minimal
          toolchain: ${{ env.RUST_STABLE }}
          components: clippy
          default: true

      - uses: Swatinem/rust-cache@d12701459954fec471b2d34cdf7ea3374b026383 # v1

      - name: cargo clippy
        working-directory: ${{ env.RUST_WORKSPACE }}
        run: cargo clippy --all-targets -- --deny warnings

  cargo-test:
    name: cargo-test
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Install ${{ env.RUST_STABLE }} toolchain
        id: rust-toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          profile: minimal
          toolchain: ${{ env.RUST_STABLE }}
          default: true

      - uses: Swatinem/rust-cache@d12701459954fec471b2d34cdf7ea3374b026383 # v1

      - name: Run tests
        env:
          RUSTFLAGS: "-D warnings"
        working-directory: ${{ env.RUST_WORKSPACE }}
        run: |
          cargo test --all-targets --quiet
          cargo test --doc --quiet
