name: Scheduled Cleanup repo

on:
  push:
  schedule:
    - cron: '30 00 * * sun'
  workflow_dispatch:
    inputs:
        number_days_old:
            description: "pass this value, all the files older than this value will be deleted from our repository. By default, this value is set to 30 days."
            required: false
            default: 30
        artifactory_name:
            description: "deletion by the name of the artifactory_name"
            required: false

jobs:
  jfrog_packages_cleanup:
     name: install jfrog cli
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: jfrog/setup-jfrog-cli@v2
         env:
           JF_ENV_DEVOPS: ${{secrets.JF_SECRET_ENV_DEVOPS}}
       - run: |
           if [ -n ${{inputs.artifactory_name}} ]; then
           sed -i 's/"name":.*/"name": {"$match":"${{inputs.artifactory_name}}"},/g' .github/scripts/artifactory.spec
           fi
           sed -i 's/number_days_limit/${{inputs.number_days_old}}/g' .github/scripts/artifactory.spec
           jf c use xayn
           cat .github/scripts/artifactory.spec
           # Ping xayn Artifactory server
           jf rt ping
           jf rt del --spec .github/scripts/artifactory.spec
