name: Scheduled Cleanup repo

on:
  push:
  schedule:
    - cron: '30 00 * * sun'
  workflow_dispatch:
    inputs:
        number_days_old:
            description: "pass this value, all the files older than this value will be deleted from our repository. By default, this value is set to 30 days."
            required: false
            default: 30 
        branch_name:
            description: "deletion by the name of the branch_name"
            required: false
            default: ""

jobs:
  jfrog_packages_cleanup:
     name: install jfrog cli
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: jfrog/setup-jfrog-cli@v2
         env:
           JF_ENV_DEVOPS: ${{secrets.JF_SECRET_ENV_DEVOPS}}
       - run: |
           if [ -n "${{inputs.branch_name}}" ]; then
           sed -i 's/"path":.*/"path": {"$match":"${{inputs.branch_name}}"},/g' .github/scripts/artifactory.spec
           fi
           
           if [ -n "${{inputs.number_days_old}}" ]; then
            sed -i 's/number_days_limit/${{inputs.number_days_old}}/g' .github/scripts/artifactory.spec
           fi
           
           jf c use xayn
           cat .github/scripts/artifactory.spec
           # Ping xayn Artifactory server
           jf rt ping
           jf rt s --spec .github/scripts/artifactory.spec
