name: Scheduled Cleanup repo

on:
  push:
  #schedule:
   # - cron: '30 00 * * sun'
  #workflow_dispatch:
   # inputs:
    #    number_days_old:
     #       description: "pass this value, all the files older than this value will be deleted from our repository. By default, this value is set to 30 days."
      #      required: false
       #     default: 30
        #artifactory_name:
         #   description: "deletion by the name of the artifactory_name"

jobs:
  jfrog_packages_cleanup:
     env:
        number_days_old: 29
        artifactory_name: "main"
     name: install jfrog cli
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: jfrog/setup-jfrog-cli@v2
         env:
           JF_ENV_DEVOPS: ${{secrets.JF_SECRET_ENV_DEVOPS}}
       - run: |
           #sed -i 's/dddd/${{github.event.inputs.number_days_old}}' .github/scripts/artifactory.spec
           #sed -i 's/name_artifactory/${{github.event.inputs.artifactory_name}}' .github/scripts/artifactory.spec
           
           if [${{artifactory_name}} != : ]; then
           sed -i '/15/ i ${{artifactory_name}}' .github/scripts/artifactory.spec
           fi

           sed -i 's/dddd/${{number_days_old}}' .github/scripts/artifactory.spec
           jf c use xayn
           # Ping xayn Artifactory server
           jf rt ping
           jf rt del --spec .github/scripts/artifactory.spec
